server:   
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: HotelAPIGateWay
 cloud:
     gateway:
       routes:
       
       - id: Location
         uri: http://localhost:8081/
         predicates:
         - Path=/api/v1/**
       - id: RoomSelection1Module
         uri: http://localhost:8082/
         predicates:
         - Path=/api/v1/**
       - id: HotelSelectionModule
         uri: http://localhost:8084/
         predicates:
         - Path=/api/v1/**